---
storage_service:
  - name: Storage-C
    display_name: Storage C
    hardware_types:
      - flash-array-c
  - name: Storage-X
    display_name: Storage X
    hardware_types:
      - flash-array-x
  - name: generic
    display_name: generic
    hardware_types:
      - flash-array-c
      - flash-array-x

storage_class:
  # Storage Classes for Storage-C
  - name: capacity
    display_name: capacity
    storage_service: Storage-C
    iops_limit: 1000
    bw_limit: 100M
    size_limit: 5T
  - name: boot
    display_name: boot
    storage_service: Storage-C
    iops_limit: 1000
    bw_limit: 5M
    size_limit: 500G

  # Storage Classes for Storage-X
  - name: ultra
    display_name: ultra
    storage_service: Storage-X
    iops_limit: 20000
    bw_limit: 2G
    size_limit: 1T
  - name: performance
    display_name: performance
    storage_service: Storage-X
    iops_limit: 10000
    bw_limit: 1G
    size_limit: 1T
  - name: bulk-VM
    display_name: bulk VM
    storage_service: Storage-X
    iops_limit: 16000
    bw_limit: 256M
    size_limit: 16T

  # Storage Classes for generic
  - name: db_standard
    display_name: db_standard
    storage_service: generic
    iops_limit: 5000
    bw_limit: 250M
    size_limit: 100T
  - name: db_bulk
    display_name: db_bulk
    storage_service: generic
    iops_limit: 1000
    bw_limit: 50M
    size_limit: 100T
  - name: db_high_performance
    display_name: db_high_performance
    storage_service: generic
    iops_limit: 10000
    bw_limit: 500M
    size_limit: 100T
