---
prefix_disk: "3624a9370"
run_fio: false

tenant_space:
  - name: ts1
    display_name: ts1
    tenant: Tenant-2

placement_groups:
  - name: pg1
    display_name: data-vols
    storage_service: Storage-X
    tenant: Tenant-2
    tenant_space: ts1
    availability_zone: AZ-1
    region: pure-us-west

volumes:
  - name: vol1
    display_name: vol1
    size: 4M
    storage_class: performance
    tenant: Tenant-2
    tenant_space: ts1
    placement_group: pg1
    host_access_policies: ["myhost"]
    mount_path: /mnt/data_vol1
