---
# tasks file for pure_fb_filesystem_failback
- name: failback | Include task for failback
  include: failback.yml repl_vars={{repl_loop.value}}
  loop: "{{ FSReplication|dict2items }}"
  loop_control:
    loop_var: repl_loop
