---
- name: Install nfs-utils and mount filesystems on clients
  block:
  - name: packages | Install nfs-utils packages
    include: packages.yml

  - name: opts | Get mount options from existing File System mount
    set_fact:
      mount_opts: "{{ item.options }}"
    loop: "{{ ansible_mounts }}"
    when: item.mount == mount.mount_point
    loop_control:
      label: "{{ item.mount }}"

  - name: unmount | Unmout all the clients from destination File System
    mount:
      path: "{{ mount.mount_point }}"
      state: absent
    become: true

  - name: mount | Mount back the clients to source File System
    mount:
      path: "{{ mount.mount_point }}"
      state: mounted
      fstype: nfs
      opts: "{{ mount_opts | default(omit) }}"
      src: "{{ src_data_vip }}:/{{ repl_vars.src.fileshare  }}"
    become: true
  when: mount.hosts in group_names or mount.hosts == inventory_hostname or mount.hosts == ansible_hostname
