---

# Example playbook to create an API token from a FlashArray for use in playbooks
#
# Note: the username and password in the vars sectrion must be valid for the FlashArray
#       you are connecting to.
#
- name: Create token for FlashArray
  hosts: localhost
  gather_facts: no
  vars:
    arrayurl: 10.234.112.107
    api_version: "1.6"
    username: pureuser
    password: pureuser

  tasks:
    - name: open session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/apitoken
        method: POST
        validate_certs: no
        return_content: yes
        body:
          username: "{{ username }}"
          password: "{{password }}"
        body_format: json
      register: token

    - name: display token
      debug: msg="{{  token.json }}"

