---
- name: network | Include task to setup network
  include: network.yml fb_vars={{outer_loop.value}}
  loop: "{{ array_inventory | combine(array_secrets, recursive=True) | dict2items }}"
  loop_control:
    loop_var: outer_loop
