---
- name: Install libselinux python package
  yum:
    name: "{{ ( (ansible_distribution_major_version | int) < 8) | ternary('libselinux-python','python3-libselinux') }}"
    state: present
  when: ansible_distribution|lower == "centos"
  become: true

- name: Install nfs-utils package on centos
  yum:
    name: nfs-utils
    state: present
  when: ansible_distribution|lower == "centos"
  become: true

- name: Install nfs-common package on ubuntu
  apt:
    name: nfs-common
  become: true
  when: ansible_distribution|lower == "ubuntu"

- name: Selinux config
  block:
  - name: Set SELinux to disabled state
    selinux:
      state: disabled
    register: selinux_reboot_required
    when: ansible_distribution|lower == "centos"

  - name: Reboot the vm when required by SELinux 
    reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: selinux_reboot_required is defined and selinux_reboot_required.reboot_required | bool
  when: ansible_distribution|lower == "centos"

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: Set bridge-nf-call-iptables (just to be sure)
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Remove swap volumes from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'
  register: remove_swap_volumes

- name: Disable SWAP
  command: swapoff -a
  when: remove_swap_volumes is changed
