---
# tasks file for pure_fb_filesystem_failover
- name: failover | Include task for failover
  include: failover.yml repl_vars={{repl_loop.value}}
  loop: "{{ FSReplication|dict2items }}"
  loop_control:
    loop_var: repl_loop
