---
- name: validation | Check connectivity for FBServer
  shell: ping -q -c 4 -W 1 {{ fb_vars.fb_host }}
  register: fb_ping_status
  failed_when: false
  changed_when: false

- name: validation | Fail if Flashblade server not reachable
  fail:
    msg: FB server {{ fb_vars.fb_host }} not reachable
  when: "'100% packet loss' in fb_ping_status.stdout"

- name: setup object-store
  include_tasks: setup_object-store.yml
  loop: "{{ fb_vars.object_store | default([]) }}"
  loop_control:
    loop_var: s3_var
  when: s3_var is defined and (s3_var|default([])|length > 0)
