- name: Pure Storage storage module examples
  hosts: localhost 
  gather_facts: false

  tasks:

#  - setup:
#      filter: ansible_devices

#  - name: "Display LUNS"
#    debug: msg="{{ item.value }}"
#    with_dict: "{{ ansible_devices }}"
#    when: '"dm-uuid-mpath-3624a937050c939582b0f46c000095416" in item.value.holder'

#  - meta: end_play

  - name: Create new volume ansible_data
    purefa_volume:
      name: ansible_data
      size: 1T
 
  - name: Create new protection group demoPG and connect volumes
    purefa_pg:
      pgroup: demoPG
      volume:
        - ansible_data
      enabled: False
 
  - name: take snapshot of demoPG
    purefa_pgsnap:
      name: demoPG
      suffix: snap

  - name: Connect volume ansible_data to host z-oracle
    purefa_host:
      host: z-oracle
      volume: ansible_data

#  - meta: end_play

  - pause:

  - name: Disconnect volume ansible_data from host z-oracle
    purefa_host:
      host: z-oracle
      volume: ansible_data

 
  - name: Eradicate demoPG snapshot
    purefa_pgsnap:
      name: demoPG
      suffix: snap
      eradicate: true
      state: absent
 
  - name: Remove volume protection group
    purefa_pg:
      pgroup: demoPG
      state: absent
      eradicate: true
 
  - name: Delete data volume
    purefa_volume:
      name: ansible_data
      state: absent
      eradicate: true
