---
#######################################################
# Windows Powershell MS SQL Database refresh 
- name:  PowerShell MS SQL Database refresh 
  hosts: z-stn-win2016-a 
  gather_facts: no
  vars_files:
    - vars/ps.yaml

  tasks:

# PowerShell database refresh
  - name: PowerShell Database Snapshot   
    win_shell: |
      New-PfaDbSnapshot -Database    'tpch-no-compression' `
             -SqlInstance {{ dbSource }} `
             -PfaEndpoint {{ pEndpoint }} `
             -PfaUser     {{ pUser }}  `
             -PfaPassword {{ pPassword }}  
    args:
      chg_dir: "{{ tgt_dir }}"
    register: snapshot

  - set_fact:
      sName: "{{snapshot.stdout_lines | select('match','name.*') | list | first}}"

  - set_fact:
      snapName: "{{ sName[10:] }}"

#  - debug: 
#      msg: "Refreshing database using snapshot name {{ snapName }}"

  - name: PowerShell Database Refesh
    win_shell: |
      Invoke-PfaDbRefresh -RefreshDatabase tpch-no-compression `
             -RefreshSource   {{ snapName }} `
             -DestSqlInstance {{ dbTarget }} `
             -PfaEndpoint     {{ pEndpoint }} `
             -PfaUser         {{ pUser }} `
             -PfaPassword     {{ pPassword }} `
             -RefreshFromSnapshot `
             -NoPsRemoting
    register: refresh

  - debug: msg="{{ refresh.stdout_lines }}"
