---
#######################################################
# Windows Powershell Test
- name:  PowerShell Test
  hosts: z-stn-win2016-a 
  gather_facts: no
  vars_files:
    - vars/ps.yaml

  tasks:

#Set-up
    - name: Copy PowerShell 'Database Refresh' script
      win_template: src=templates/databaseRefresh.ps1.j2 dest={{ tgt_dir }}\databaseRefresh.ps1


    - name: Execute Database Refresh PowerShell script
      win_shell: C:\Users\devops\.ansible\databaseRefresh.ps1
      args:
        chg_dir: "{{ tgt_dir }}"
      register: out 

    - debug: var=out.stdout_lines
