---
- name: Drift Control | FlashArray
  include_tasks:
    file: "all_fa.yaml"
  vars:
    url: "{{ item.url }}"
    api: "{{ item.api }}"
  with_items: "{{ arrays }}"
  no_log: True

- name: Drift Control | FlashBlade
  include_tasks:
    file: "all_fb.yaml"
  vars:
    url: "{{ item.url }}"
    api: "{{ item.api }}"
  with_items: "{{ blades }}"
  no_log: True
