---

# Example playbook to list volumes pending eradication after deletion on a FlashArray
#
# No parameters are required for this playbook
# 
- name: List pending volumes on FlashArray
  hosts: localhost
  gather_facts: no
  vars:
    arrayurl: 10.234.112.107
    array_token: e31060a7-21fc-e277-6240-25983c6c4592
    api_version: "1.6"

  tasks:
    - name: open session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: POST
        validate_certs: no
        return_content: yes
        body:
          api_token: "{{ array_token }}"
        body_format: json
      register: session

    - name: list pending volumes
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/volume?pending_only=true
        method: GET
        validate_certs: no
        HEADER_Cookie: "{{session.set_cookie}}"
        return_content: yes
      ignore_errors: yes
      register: pendingvoldata

    - name: show pendin gvolume list
      debug: msg="{{ pendingvoldata.json }}"
