---

# Example playbook to detach a volume to a host on a FlashArray
#
# Provide the following parameters to the ansible-playbook command 
# using the -e switch:
# 
#   -e "hostname=host-name volname=volume-name"
#
# For example:
#
#  ansible-playbook flasharray_detach_volume.yaml -e "hostname=test-host volname=test-vol"
# 
# Note: this playbook assumes that the volume is already attached to the host.
#
- name: Detach volume on FlashArray
  hosts: localhost
  gather_facts: no
  vars:
    arrayurl: 10.234.112.107
    array_token: e31060a7-21fc-e277-6240-25983c6c4592
    api_version: "1.6"

  tasks:
    - name: open session
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/auth/session
        method: POST
        validate_certs: no
        return_content: yes
        body:
          api_token: "{{ array_token }}"
        body_format: json
      register: session

    - name: detach volume
      uri:
        url: https://{{ arrayurl }}/api/{{ api_version }}/host/{{ hostname }}/volume/{{ volname }}
        method: DELETE
        validate_certs: no
        HEADER_Cookie: "{{session.set_cookie}}"
        return_content: yes
      ignore_errors: yes
