---
  - name: Drift Control | FlashArray | Get facts for {{ url }}
    purestorage.flasharray.purefa_info:
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
      gather_subset:
      - config
      - minimum
    register: array_info

  - name: Drift Control | FlashArray | Set facts
    set_fact:
      array_name: "{{ array_info.purefa_info.default.array_name }}"
      full_array_name: "{{ array_info.purefa_info.default.array_name + '[' + dc + ']' }}"
      array_version: "{{ array_info.purefa_info.default.purity_version }}"

  - name: Drift Control | FlashArray | DNS for {{ full_array_name }}
    purestorage.flasharray.purefa_dns:
      domain: "{{ vars[dc + '_dns_domain] }}"
      nameservers: "{{ vars[dc + '_dns_address] }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    check_mode: yes
    register: dns_change

  - name: Drift Control | FlashArray | Slack alert for DNS on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect DNS configuration"
    when: dns_change.changed

  - name: Drift Control | FlashArray | NTP for {{ full_array_name }}
    purestorage.flasharray.purefa_ntp:
      ntp_servers: "{{ vars[dc + '_ntp_servers'] }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    check_mode: yes
    register: ntp_change

  - name: Drift Control | FlashArray | Slack alert for NTP on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect NTP configuration"
    when: ntp_change.changed

  - name: Drift Control | FlashArray | Banner for {{ full_array_name }}
    purestorage.flasharray.purefa_banner:
      banner: "{{ array_name }} [{{ dc }}] ({{ array_info.purefa_info.default.purity_version }})\n              ---------              \n     Do Not Use Without Permission"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    check_mode: yes
    register: banner_change
  
  - name: Drift Control | FlashArray | Slack alert for Banner on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect Banner configuration"
    when: banner_change.changed


  - name: Drift Control | FlashArray | SMTP for {{ full_array_name }}
    purestorage.flasharray.purefa_smtp:
      sender_domain: "{{ vars[dc + '_smtp_domain'] }}"
      relay_host: "{{ vars[dc + '_smtp_relay'] }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    check_mode: yes
    register: smtp_change

  - name: Drift Control | FlashArray | Slack alert for SMTP on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect SMTP configuration"
    when: smtp_change.changed

  - name: Drift Control | FlashArray | syslog for {{ full_array_name }}
    purestorage.flasharray.purefa_syslog:
      protocol: "{{ syslog_protocol }}"
      address: "{{ vars[dc + '_syslog_address'] }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    check_mode: yes
    register: syslog_change

  - name: Drift Control | FlashArray | Slack alert for syslog on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect syslog configuration"
    when: syslog_change.changed

  - name: Drift Control | FlashArray | Alert Email for {{ full_array_name }}
    purestorage.flasharray.purefa_alert:
      address: "{{ alert_address }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    check_mode: yes
    register: alert_change

  - name: Drift Control | FlashArray | Slack alert for Alert email on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect Alert email configuration"
    when: alert_change.changed

  - name: Drift Control | FlashArray | GUI Timeout for {{ full_array_name }}
    purestorage.flasharray.purefa_timeout:
      timeout: "{{ timeout }}"
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
    check_mode: yes
    register: gui_change

  - name: Drift Control | FlashArray | Slack alert for GUI Timeout on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect GUI Timeout configuration"
    when: gui_change.changed

  - name: Drift Control | FlashArray | Active Directory roles for {{ full_array_name }}
    purestorage.flasharray.purefa_dsrole:
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
      role: "{{ vars[dc + '_ad_item.name'] }}"
      group_base: "{{ vars[dc + '_ad_item.group_base'] }}"
      group: "{{ vars[dc + '_ad_item.group'] }}"
      state: "{{ vars[dc + '_ad_item.state'] }}"
    loop_control:
      loop_var: dc + '_ad_item'
    loop:
      - name: array_admin
        group_base: "{{ vars[dc + '_ad_admin_base'] }}"
        group: "{{ vars[dc + '_ad_admin_group'] }}"
        state: present
      - name: readonly
        group_base: "{{ vars[dc + '_ad_ro_base'] }}"
        group: "{{ ad_ro_group' }}"
        state: present
      - name: ops_admin
        group_base: null
        group: null 
        state: absent
      - name: storage_admin
        group_base: null
        group: null 
        state: absent
    check_mode: yes
    register: ad_role_change

  - name: Drift Control | FlashArray | Slack alert for AD Role on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect NTP configuration"
    when: ad_role_change.changed

  - name: Drift Control | FlashArray | Management Active Directory for {{ full_array_name }}
    purestorage.flasharray.purefa_ds:
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
      enable: true
      dstype: management
      uri: "{{ vars[dc + '_mgmt_ad_uri'] }}"
      base_dn: "{{ vars[dc + '_mgmt_ad_base'] }}"
      bind_user: "{{ vars[dc + '_mgmt_fa_ad_user'] }}"
    check_mode: yes
    register: mgmt_ad_change

  - name: Drift Control | FlashArray | Slack alert for Mgmt AD on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect Mgmt AD configuration"
    when: mgmt_ad_change.changed

  - name: Drift Control | FlashArray | Data Active Directory for {{ full_array_name }}
    purestorage.flasharray.purefa_ds:
      fa_url: "{{ url }}"
      api_token: "{{ api }}"
      enable: false
      dstype: data
      uri: "{{ vars[dc + '_data_ad_uri'] }}"
      base_dn: "{{ vars[dc + '_data_ad_base'] }}"
      bind_user: "{{ vars[dc + '_data_fa_ad_user'] }}"
    when: array_version.split('.')[0]|int == 6
    check_mode: yes
    register: data_ad_change

  - name: Drift Control | FlashArray | Slack alert for Data AD on {{ full_array_name }}
    local_action:
      module: slack
      token: "{{ slack_token }}"
      msg: "Array {{ full_array_name }} has incorrect Data AD configuration"
    when: data_ad_change.changed
