---
  - name: Drift Control | FlashBlade | Get facts for {{ url }}
    purestorage.flashblade.purefb_info:
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
    register: blade_info

  - name: Drift Control | FlashBlade | Set facts
    set_fact:
      blade_name: "{{ blade_info.purefb_info.default.flashblade_name }}"
      full_blade_name: "{{ blade_info.purefb_info.default.flashblade_name + '[' + dc + ']'}}"
      blade_version: "{{ blade_info.purefb_info.default.purity_version }}"

  - name: Drift Control | FlashBlade | DNS for {{ full_blade_name }}
    purestorage.flashblade.purefb_dns:
      domain: "{{ vars[dc + '_dns_domain'] }}"
      nameservers: "{{ vars[dc + '_dns_address'] }}"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"

  - name: Drift Control | FlashBlade | NTP for {{ full_blade_name }}
    purestorage.flashblade.purefb_ntp:
      ntp_servers: "{{ vars[dc + '_ntp_servers'] }}"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"

  - name: Drift Control | FlashBlade | Banner for {{ full_blade_name }}
    purestorage.flashblade.purefb_banner:
      banner: "{{ blade_name }} [{{ dc }}] ({{ blade_info.purefb_info.default.purity_version }})\n                 ---------                 \n        Do Not Use Without Permission"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"

  - name: Drift Control | FlashBlade | SMTP for {{ full_blade_name }}
    purestorage.flashblade.purefb_smtp:
      domain: "{{ vars[dc + '_smtp_domain'] }}"
      host: "{{ vars[dc + '_smtp_relay'] }}"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"

  - name: Drift Control | FlashBlade | syslog for {{ full_blade_name }}
    purestorage.flashblade.purefb_syslog:
      name: syslog1
      protocol: "{{ syslog_protocol }}"
      address: "{{ vars[dc + '_syslog_address'] }}"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"

  - name: Drift Control | FlashBlade | Alert Email for {{ full_blade_name }}
    purestorage.flashblade.purefb_alert:
      address: "{{ alert_address }}"
      fb_url: "{{ url }}"
      api_token: "{{ api }}"

  - name: Drift Control | FlashBlade | Active Directory Roles for {{ full_blade_name }}
    purestorage.flashblade.purefb_dsrole:
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
      role: "{{ vars[dc + '_ad_item.name'] }}"
      group_base: "{{ vars[dc + '_ad_item.group_base'] }}"
      group: "{{ vars[dc + '_ad_item.group'] }}"
      state: "{{ vars[dc + '_ad_item.state'] }}"
    loop_control:
      loop_var: dc + '_ad_item'
    loop:
      - name: array_admin
        group_base: "{{ vars[dc + '_ad_admin_base'] }}"
        group: "{{ vars[dc + '_ad_admin_group'] }}"
        state: present
      - name: readonly
        group_base: "{{ vars[dc + '_ad_ro_base'] }}"
        group: "{{ vars[dc + '_ad_ro_group'] }}"
        state: present
      - name: ops_admin
        group_base: null
        group: null 
        state: absent
      - name: storage_admin
        group_base: null
        group: null 
        state: absent

  - name: Drift Control | FlashBlade | Active Directory for {{ full_blade_name }}
    purestorage.flashblade.purefb_ds:
      fb_url: "{{ url }}"
      api_token: "{{ api }}"
      enable: true
      uri: "{{ vars[dc + '_ad_item.uri'] }}"
      base_dn: "{{ vars[dc + '_ad_item.base'] }}"
      bind_user: "{{ vars[dc + '_ad_item.user'] }}"
      bind_password: "{{ vars[dc + '_ad_item.password'] }}" 
      dstype: "{{ vars[dc + '_ad_item.type'] }}"
    loop_control:
      loop_var: ad_item
    loop:
      - type: management
        uri: "{{ vars[dc + '_mgmt_ad_uri'] }}"
        base: "{{ vars[dc + '_mgmt_ad_base'] }}"
        user: "{{ vars[dc + '_fb_ad_user'] }}"
        password: "{{ vars[dc + '_mgmt_ad_password'] }}"
      - type: smb
        uri: "{{ vars[dc + '_smb_uri'] }}"
        base: "{{ vars[dc + '_mgmt_ad_base'] }}"
        user: "{{ vars[dc + '_smb_user'] }}"
        password: "{{ vars[dc + '_mgmt_ad_password'] }}"
    no_log: True
